name: Java CI with Maven and Auto Tagging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn -B test

    # - name: Bump version and push tag
    #   id: tag_version
    #   uses: mathieudutour/github-tag-action@v5.6
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     default_bump: patch
    #     initial_version: '1.0.0' # Sets the initial version if no tags exist
    #     release_branches: main  # Ensures tags are only pushed on the main branch

    - name: Upload Artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: application
        path: target/educai.jar
        
    - name: Deploy to Azure VM
      uses: appleboy/scp-action@v0.1.7
      with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.AZURE_VM_PORT }}
          source: "target/educai.jar"
          target: "/home/educai/"
