name: Java CI with Maven and Auto Tagging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn -B test

    # - name: Bump version and push tag
    #   id: tag_version
    #   uses: mathieudutour/github-tag-action@v5.6
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     default_bump: patch
    #     initial_version: '1.0.0' # Sets the initial version if no tags exist
    #     release_branches: main  # Ensures tags are only pushed on the main branch

    - name: Upload Artifact
      id: upload-artifact
      uses: actions/upload-artifact@v2
      with:
        name: application
        path: target/*.jar

    - name: Get Artifact URL
      id: get-artifact-url
      run: |
        artifact_path=$(find $GITHUB_WORKSPACE -name "*.jar")
        echo "::set-output name=url::$(echo \"https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts/${artifact_path}\")"
        
    - name: Deploy to Azure VM
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az login --service-principal -u ${{ secrets.AZURE_SERVICE_PRINCIPAL }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az vm extension set \
            --resource-group Educ.AI \
            --vm-name Educ.AI \
            --name customScript \
            --publisher Microsoft.Azure.Extensions \
            --settings '{"fileUris":["${{ steps.get-artifact-url.outputs.url }}"],"commandToExecute":"java -jar application.jar"}'
