name: Java CI with Maven and Auto Tagging

on:
  push:
    branches: [ feat/githubSecrets ]

jobs:
  CI:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn -B test

    - name: Configure Environment Variables
      run: |
          sed -i 's/\$\{\{ secrets.AZURE_STORAGE_CONNECTION_STRING \}\}/'"${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"'/g' application.properties
          sed -i 's/\$\{\{ secrets.AZURE_STORAGE_CONTAINER_NAME \}\}/'"${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}"'/g' application.properties
          sed -i 's/\$\{\{ secrets.MONGO_PORT \}\}/'"${{ secrets.MONGO_PORT }}"'/g' application.properties
          sed -i 's/\$\{\{ secrets.MONGO_HOST \}\}/'"${{ secrets.MONGO_HOST }}"'/g' application.properties
          sed -i 's/\$\{\{ secrets.MONGO_PORT \}\}/'"${{ secrets.MONGO_DB }}"'/g' application.properties
          sed -i 's/\$\{\{ secrets.MONGO_HOST \}\}/'"${{ secrets.MONGO_USERNAME }}"'/g' application.properties
          sed -i 's/\$\{\{ secrets.MONGO_PASSWORD \}\}/'"${{ secrets.MONGO_PASSWORD }}"'/g' application.properties


    # - name: Bump version and push tag
    #   id: tag_version
    #   uses: mathieudutour/github-tag-action@v5.6
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     default_bump: patch
    #     initial_version: '1.0.0' # Sets the initial version if no tags exist
    #     release_branches: main  # Ensures tags are only pushed on the main branch

    - name: Upload Artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: application
        path: target/*.jar

  CD:
    needs: [CI]
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
          name: application
          path: target/
          
    - name: Deploy to Azure VM
      uses: appleboy/scp-action@v0.1.7
      with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.AZURE_VM_PORT }}
          source: "target/*.jar"
          target: "/home/educai/java-app"

    - name: Move Java App to Docker Container
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.AZURE_VM_PORT }}
        script: |
          chmod +x /home/educai/script-backend.sh
          sh /home/educai/script-backend.sh
